version: '2'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - photos:/app/photos

volumes:
  photos:
